version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    container_name: shopitall-server
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGODB_URI=mongodb+srv://natanaeljavierj0002_db_user:3TDDsyXhQyMBSPDK@shopitallproduct.husgnpy.mongodb.net/shopitall?retryWrites=true&w=majority
    ports:
      - "4000:4000"

  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    container_name: shopitall-client
    environment:
      - REACT_APP_API_URL=http://20.28.46.177:4000
    ports:
      - "3000:80"
    depends_on:
      - server
